[package]
name = "termo-solver"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = 3

[dependencies]
float-ord = "0.3.2"
unroll = "0.1.5"